name: my_shop_ecommerce_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.10
  flutter_stripe: ^1.3.0
  pay: ^1.0.1
  http: ^0.13.1
  intl: ^0.17.0
  uuid: ^3.0.4
  rxdart: ^0.27.2
  freezed_annotation: ^0.14.3
  mocktail: ^0.2.0
  # Is there any way to not include these dependencies on macOS?
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  cloud_functions: ^3.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^0.14.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
