name: my_shop_ecommerce_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0
  flutter_stripe: ^2.1.0
  flutter_stripe_web: 0.1.0
  pay: ^1.0.6
  http: ^0.13.1
  intl: ^0.17.0
  uuid: ^3.0.4
  rxdart: ^0.27.2
  freezed_annotation: ^1.1.0
  sembast: ^3.1.1
  sembast_web: ^2.0.1+1
  path_provider: ^2.0.6
  # Is there any way to not include these dependencies on macOS?
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  cloud_functions: ^3.2.3
  flutter_layout_grid: ^1.0.3
  go_router: ^2.5.7
  cached_network_image: ^3.2.0
  gap: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^1.1.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
