name: my_shop_ecommerce_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  flutter_stripe: ^1.3.0
  pay: ^1.0.1
  http: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
