name: my_shop_ecommerce_flutter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  flutter_stripe: ^6.0.0
  flutter_stripe_web: ^2.0.1
  pay: ^1.0.11
  intl: ^0.17.0
  uuid: ^3.0.5
  rxdart: ^0.27.3
  sembast: ^3.1.2
  sembast_web: ^2.0.1+1
  path_provider: ^2.0.8
  # Is there any way to not include these dependencies on macOS?
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  cloud_functions: ^3.2.6
  flutter_layout_grid: ^2.0.1
  go_router: ^3.0.2
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  freezed_annotation: ^2.0.3
  multiple_result: ^1.0.4
  sentry_flutter: ^6.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  build_runner: ^2.1.7
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/products/
